export enum AccountStatus {
    PENDING_VERIFICATION = "PENDING_VERIFICATION",
    PENDING_APPROVAL = "PENDING_APPROVAL",
    ACTIVE = "ACTIVE",
    SUSPENDED = "SUSPENDED",
    REJECTED = "REJECTED",
}