export const CONFIG = {
    BCRYPT_SALT_ROUNDS: 12,

    OTP_LENGTH: 6,
    OTP_EXPIRY_MINUTES: 10,
    OTP_MAX_ATTEMPTS: 5,

    ACCESS_TOKEN_EXPIRES_IN: "7d",
    RESET_TICKET_EXPIRES_IN: "10m",
    EMAIL_VERIFY_TICKET_EXPIRES_IN: "15m",

    PAGINATION_DEFAULT_PAGE: 1,
    PAGINATION_DEFAULT_LIMIT: 20,
    PAGINATION_MAX_LIMIT: 100,

    PASSWORD_MIN_LENGTH: 8,
    PASSWORD_MAX_LENGTH: 128,
    PASSWORD_HISTORY_LIMIT: 5,

    RATE_LIMIT_WINDOW_MS: 900_000,
    RATE_LIMIT_MAX: 100,

    AUTH_RATE_LIMIT_MAX: 5,
    INQUIRY_RATE_LIMIT_MAX: 3,
} as const;