export const ERROR_CODES = {
    // Auth
    AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
    AUTH_TOKEN_MISSING: "AUTH_TOKEN_MISSING",
    AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
    AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
    AUTH_FORBIDDEN: "AUTH_FORBIDDEN",
    AUTH_ACCOUNT_INACTIVE: "AUTH_ACCOUNT_INACTIVE",
    AUTH_EMAIL_NOT_VERIFIED: "AUTH_EMAIL_NOT_VERIFIED",
    AUTH_ACCOUNT_PENDING_APPROVAL: "AUTH_ACCOUNT_PENDING_APPROVAL",

    // Registration
    REG_EMAIL_EXISTS: "REG_EMAIL_EXISTS",
    REG_PHONE_EXISTS: "REG_PHONE_EXISTS",
    REG_WEAK_PASSWORD: "REG_WEAK_PASSWORD",

    // OTP
    OTP_INVALID: "OTP_INVALID",
    OTP_EXPIRED: "OTP_EXPIRED",
    OTP_MAX_ATTEMPTS: "OTP_MAX_ATTEMPTS",
    OTP_NOT_FOUND: "OTP_NOT_FOUND",

    // Password
    PWD_CURRENT_WRONG: "PWD_CURRENT_WRONG",
    PWD_SAME_AS_OLD: "PWD_SAME_AS_OLD",

    // User
    USER_NOT_FOUND: "USER_NOT_FOUND",
    USER_INACTIVE: "USER_INACTIVE",
    INVALID_ID: "INVALID_ID",

    // Employee
    EMP_NOT_FOUND: "EMP_NOT_FOUND",
    EMP_TRADE_REQUIRED: "EMP_TRADE_REQUIRED",
    EMP_ALREADY_REVIEWED: "EMP_ALREADY_REVIEWED",

    // Client
    CLIENT_NOT_FOUND: "CLIENT_NOT_FOUND",
    CLIENT_ACCESS_DENIED: "Client access denied",

    // Inquiry
    INQ_NOT_FOUND: "INQ_NOT_FOUND",
    INQ_ALREADY_CONVERTED: "INQ_ALREADY_CONVERTED",

    // Site
    SITE_NOT_FOUND: "SITE_NOT_FOUND",
    SITE_ACCESS_DENIED: "SITE_ACCESS_DENIED",

    // Task
    TASK_NOT_FOUND: "TASK_NOT_FOUND",
    TASK_INVALID_TRANSITION: "TASK_INVALID_TRANSITION",

    // Floor Plan
    FP_NOT_FOUND: "FP_NOT_FOUND",
    FP_ALREADY_REVIEWED: "FP_ALREADY_REVIEWED",

    // Generic
    VALIDATION_ERROR: "VALIDATION_ERROR",
    INTERNAL_ERROR: "INTERNAL_ERROR",
    RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
    DUPLICATE_KEY: "DUPLICATE_KEY",
    ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
} as const;

export type ErrorCode =
    typeof ERROR_CODES[keyof typeof ERROR_CODES];