export const PERMISSIONS = {
    // Users
    USER_VIEW: "USER_VIEW",
    USER_UPDATE: "USER_UPDATE",
    USER_DELETE: "USER_DELETE",
    USER_ACTIVATE: "USER_ACTIVATE",
    USER_DEACTIVATE: "USER_DEACTIVATE",

    // Employees
    EMPLOYEE_VIEW: "EMPLOYEE_VIEW",
    EMPLOYEE_UPDATE: "EMPLOYEE_UPDATE",
    EMPLOYEE_APPROVE: "EMPLOYEE_APPROVE",
    EMPLOYEE_REJECT: "EMPLOYEE_REJECT",

    // Clients
    CLIENT_VIEW: "CLIENT_VIEW",

    // Inquiries
    INQUIRY_VIEW: "INQUIRY_VIEW",
    INQUIRY_UPDATE: "INQUIRY_UPDATE",
    INQUIRY_ASSIGN: "INQUIRY_ASSIGN",
    INQUIRY_CONVERT: "INQUIRY_CONVERT",
    INQUIRY_DELETE: "INQUIRY_DELETE",

    // Sites
    SITE_VIEW: "SITE_VIEW",
    SITE_CREATE: "SITE_CREATE",
    SITE_UPDATE: "SITE_UPDATE",
    SITE_DELETE: "SITE_DELETE",
    SITE_PROGRESS_VIEW: "SITE_PROGRESS_VIEW",

    // Tasks
    TASK_VIEW: "TASK_VIEW",
    TASK_CREATE: "TASK_CREATE",
    TASK_UPDATE: "TASK_UPDATE",
    TASK_DELETE: "TASK_DELETE",
    TASK_STATUS_UPDATE: "TASK_STATUS_UPDATE",

    // Floor Plans
    FLOOR_PLAN_VIEW: "FLOOR_PLAN_VIEW",
    FLOOR_PLAN_CREATE: "FLOOR_PLAN_CREATE",
    FLOOR_PLAN_APPROVE: "FLOOR_PLAN_APPROVE",
    FLOOR_PLAN_REJECT: "FLOOR_PLAN_REJECT",
    FLOOR_PLAN_DELETE: "FLOOR_PLAN_DELETE",

    // Maps
    MAP_VIEW: "MAP_VIEW",
    MAP_CITY_SUMMARY: "MAP_CITY_SUMMARY",
} as const;

export type Permission =
    typeof PERMISSIONS[keyof typeof PERMISSIONS];